name: Compile

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Download Android NDK
        run: |
          curl -O https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -s
          unzip -q ./android-ndk-r21e-linux-x86_64.zip
          
      - name: Compile
        run: ./android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang mali_alias.c -o mali_alias
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: mali_alias
          path: mali_alias
