name: Compile

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup
        run: sudo apt-get install curl unzip -y

      - name: Download Android NDK
        run: |
          curl -# https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -o ndk.zip
          unzip ./ndk.zip
          
      - name: Compile
        run: ./android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang mali_alias.c -o mali_alias
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: mali_alias
          path: mali_alias
